version: '3.8'

services:
  neo4j:
    build: .
    container_name: neo4j
    environment:
      - NEO4J_AUTH=neo4j/knowledgegraphs
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data

volumes:
  neo4j_data: